<?php

/**
 * BaseSpeakoutReply
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $body
 * @property string $htmlbody
 * @property integer $topic_id
 * @property integer $networkuser_id
 * @property SpeakoutTopic $SpeakoutTopic
 * @property NetworkUser $NetworkUser
 * 
 * @method integer       getId()             Returns the current record's "id" value
 * @method string        getBody()           Returns the current record's "body" value
 * @method string        getHtmlbody()       Returns the current record's "htmlbody" value
 * @method integer       getTopicId()        Returns the current record's "topic_id" value
 * @method integer       getNetworkuserId()  Returns the current record's "networkuser_id" value
 * @method SpeakoutTopic getSpeakoutTopic()  Returns the current record's "SpeakoutTopic" value
 * @method NetworkUser   getNetworkUser()    Returns the current record's "NetworkUser" value
 * @method SpeakoutReply setId()             Sets the current record's "id" value
 * @method SpeakoutReply setBody()           Sets the current record's "body" value
 * @method SpeakoutReply setHtmlbody()       Sets the current record's "htmlbody" value
 * @method SpeakoutReply setTopicId()        Sets the current record's "topic_id" value
 * @method SpeakoutReply setNetworkuserId()  Sets the current record's "networkuser_id" value
 * @method SpeakoutReply setSpeakoutTopic()  Sets the current record's "SpeakoutTopic" value
 * @method SpeakoutReply setNetworkUser()    Sets the current record's "NetworkUser" value
 * 
 * @package    Yuoweb
 * @subpackage model
 * @author     Shadley Wentzel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSpeakoutReply extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('speakout_reply');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('body', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('htmlbody', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('topic_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('networkuser_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SpeakoutTopic', array(
             'local' => 'topic_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('NetworkUser', array(
             'local' => 'networkuser_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($timestampable0);
        $this->actAs($softdelete0);
    }
}