<?php

/**
 * BasesfMultisiteThemeProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $site_name
 * @property integer $sf_multisite_theme_theme_info_id
 * @property sfMultisiteThemeThemeInfo $sfMultisiteThemeThemeInfo
 * @property Doctrine_Collection $sfMultisiteThemeProfileHosts
 * 
 * @method string                    getSiteName()                         Returns the current record's "site_name" value
 * @method integer                   getSfMultisiteThemeThemeInfoId()      Returns the current record's "sf_multisite_theme_theme_info_id" value
 * @method sfMultisiteThemeThemeInfo getSfMultisiteThemeThemeInfo()        Returns the current record's "sfMultisiteThemeThemeInfo" value
 * @method Doctrine_Collection       getSfMultisiteThemeProfileHosts()     Returns the current record's "sfMultisiteThemeProfileHosts" collection
 * @method sfMultisiteThemeProfile   setSiteName()                         Sets the current record's "site_name" value
 * @method sfMultisiteThemeProfile   setSfMultisiteThemeThemeInfoId()      Sets the current record's "sf_multisite_theme_theme_info_id" value
 * @method sfMultisiteThemeProfile   setSfMultisiteThemeThemeInfo()        Sets the current record's "sfMultisiteThemeThemeInfo" value
 * @method sfMultisiteThemeProfile   setSfMultisiteThemeProfileHosts()     Sets the current record's "sfMultisiteThemeProfileHosts" collection
 * 
 * @package    Spark
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfMultisiteThemeProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_multisite_theme_profile');
        $this->hasColumn('site_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('sf_multisite_theme_theme_info_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfMultisiteThemeThemeInfo', array(
             'local' => 'sf_multisite_theme_theme_info_id',
             'foreign' => 'id'));

        $this->hasMany('sfMultisiteThemeProfileHost as sfMultisiteThemeProfileHosts', array(
             'local' => 'id',
             'foreign' => 'sf_multisite_theme_profile_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}