<?php

/**
 * PluginSpeakoutTopic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginSpeakoutTopic extends BaseSpeakoutTopic
{
    /**
     * Returns all replies with uers
     *
     * @return 
     */
  public function getReplys()
  {
	  $q = Doctrine_Query::create()
       ->from('SpeakoutReply sr')
       ->leftJoin('sr.NetworkUser nu')
       ->where('sr.topic_id = ?', $this->getId()); 
	
     return Doctrine_Core::getTable('NetworkUser')->getWithUsers($q);
  }
}