<?php

/**
 * PluginSpeakoutCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSpeakoutCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSpeakoutCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSpeakoutCategory');
    }
}