<?php

/**
 * PluginSpeakoutReplyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSpeakoutReplyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSpeakoutReplyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSpeakoutReply');
    }
    
    /**
     * Returns a category with all Repies and their users
     *
     * @return 
     */
	public function getReplysWithUsers(Doctrine_Query $q = null)
	{
	  if (is_null($q))
	  {
	    $q = Doctrine_Query::create()
	      ->from('NetworkUser nu');      	  
	  }
	
	  return Doctrine_Core::getTable('NetworkUser')->getWithUsers($q);
		 
	  //echo '<pre>';print_r($q->fetchArray());exit;
	}
}