<?php

/**
 * PluginSpeakoutReplyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSpeakoutReplyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSpeakoutReplyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginSpeakoutReply');
    }
}