<?php

/**
 * SpeakoutTopicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpeakoutTopicTable extends PluginSpeakoutTopicTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object SpeakoutTopicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SpeakoutTopic');
    }
}