<?php

/**
 * BaseAdvert
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property string $url
 * @property string $image_path
 * @property Doctrine_Collection $AdvertNetwork
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getTitle()         Returns the current record's "title" value
 * @method string              getDescription()   Returns the current record's "description" value
 * @method string              getUrl()           Returns the current record's "url" value
 * @method string              getImagePath()     Returns the current record's "image_path" value
 * @method Doctrine_Collection getAdvertNetwork() Returns the current record's "AdvertNetwork" collection
 * @method Advert              setId()            Sets the current record's "id" value
 * @method Advert              setTitle()         Sets the current record's "title" value
 * @method Advert              setDescription()   Sets the current record's "description" value
 * @method Advert              setUrl()           Sets the current record's "url" value
 * @method Advert              setImagePath()     Sets the current record's "image_path" value
 * @method Advert              setAdvertNetwork() Sets the current record's "AdvertNetwork" collection
 * 
 * @package    Spark
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdvert extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('advert');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('description', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('url', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('image_path', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AdvertNetwork', array(
             'local' => 'id',
             'foreign' => 'advert_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'description',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($searchable0);
    }
}