<?php

/**
 * BaseNotification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $network_id
 * @property integer $networkuser_id
 * @property integer $notificationtype_id
 * @property Network $Network
 * @property NetworkUser $NetworkUser
 * @property NotificationType $NotificationType
 * 
 * @method integer          getId()                  Returns the current record's "id" value
 * @method integer          getNetworkId()           Returns the current record's "network_id" value
 * @method integer          getNetworkuserId()       Returns the current record's "networkuser_id" value
 * @method integer          getNotificationtypeId()  Returns the current record's "notificationtype_id" value
 * @method Network          getNetwork()             Returns the current record's "Network" value
 * @method NetworkUser      getNetworkUser()         Returns the current record's "NetworkUser" value
 * @method NotificationType getNotificationType()    Returns the current record's "NotificationType" value
 * @method Notification     setId()                  Sets the current record's "id" value
 * @method Notification     setNetworkId()           Sets the current record's "network_id" value
 * @method Notification     setNetworkuserId()       Sets the current record's "networkuser_id" value
 * @method Notification     setNotificationtypeId()  Sets the current record's "notificationtype_id" value
 * @method Notification     setNetwork()             Sets the current record's "Network" value
 * @method Notification     setNetworkUser()         Sets the current record's "NetworkUser" value
 * @method Notification     setNotificationType()    Sets the current record's "NotificationType" value
 * 
 * @package    Yuoweb
 * @subpackage model
 * @author     Shadley Wentzel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotification extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notification');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('network_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('networkuser_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('notificationtype_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Network', array(
             'local' => 'network_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('NetworkUser', array(
             'local' => 'networkuser_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('NotificationType', array(
             'local' => 'notificationtype_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'network_id',
              1 => 'notificationtype_id',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($searchable0);
    }
}