<?php

/**
 * BaseFeed
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $feedtype_id
 * @property string $body
 * @property string $htmlbody
 * @property sfGuardUser $sfGuardUser
 * @property FeedType $FeedType
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method integer     getFeedtypeId()  Returns the current record's "feedtype_id" value
 * @method string      getBody()        Returns the current record's "body" value
 * @method string      getHtmlbody()    Returns the current record's "htmlbody" value
 * @method sfGuardUser getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method FeedType    getFeedType()    Returns the current record's "FeedType" value
 * @method Feed        setId()          Sets the current record's "id" value
 * @method Feed        setUserId()      Sets the current record's "user_id" value
 * @method Feed        setFeedtypeId()  Sets the current record's "feedtype_id" value
 * @method Feed        setBody()        Sets the current record's "body" value
 * @method Feed        setHtmlbody()    Sets the current record's "htmlbody" value
 * @method Feed        setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method Feed        setFeedType()    Sets the current record's "FeedType" value
 * 
 * @package    Yuoweb
 * @subpackage model
 * @author     Shadley Wentzel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFeed extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('feed');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('feedtype_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('body', 'string', 160, array(
             'type' => 'string',
             'length' => 160,
             ));
        $this->hasColumn('htmlbody', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('FeedType', array(
             'local' => 'feedtype_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $commentable0 = new Doctrine_Template_Commentable();
        $this->actAs($timestampable0);
        $this->actAs($commentable0);
    }
}