<?php

/**
 * BaseMessageReciever
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $message_id
 * @property integer $user_id
 * @property integer $messagestatus_id
 * @property sfGuardUser $sfGuardUser
 * @property Message $Message
 * @property MessageStatus $MessageStatus
 * 
 * @method integer         getId()               Returns the current record's "id" value
 * @method integer         getMessageId()        Returns the current record's "message_id" value
 * @method integer         getUserId()           Returns the current record's "user_id" value
 * @method integer         getMessagestatusId()  Returns the current record's "messagestatus_id" value
 * @method sfGuardUser     getSfGuardUser()      Returns the current record's "sfGuardUser" value
 * @method Message         getMessage()          Returns the current record's "Message" value
 * @method MessageStatus   getMessageStatus()    Returns the current record's "MessageStatus" value
 * @method MessageReciever setId()               Sets the current record's "id" value
 * @method MessageReciever setMessageId()        Sets the current record's "message_id" value
 * @method MessageReciever setUserId()           Sets the current record's "user_id" value
 * @method MessageReciever setMessagestatusId()  Sets the current record's "messagestatus_id" value
 * @method MessageReciever setSfGuardUser()      Sets the current record's "sfGuardUser" value
 * @method MessageReciever setMessage()          Sets the current record's "Message" value
 * @method MessageReciever setMessageStatus()    Sets the current record's "MessageStatus" value
 * 
 * @package    Yuoweb
 * @subpackage model
 * @author     Shadley Wentzel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMessageReciever extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('message_reciever');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('message_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('messagestatus_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Message', array(
             'local' => 'message_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('MessageStatus', array(
             'local' => 'messagestatus_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}