<?php

/**
 * BaseSpeakCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $description
 * @property integer $network_id
 * @property Network $Network
 * @property Doctrine_Collection $SpeakTopic
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getTitle()       Returns the current record's "title" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method integer             getNetworkId()   Returns the current record's "network_id" value
 * @method Network             getNetwork()     Returns the current record's "Network" value
 * @method Doctrine_Collection getSpeakTopic()  Returns the current record's "SpeakTopic" collection
 * @method SpeakCategory       setId()          Sets the current record's "id" value
 * @method SpeakCategory       setTitle()       Sets the current record's "title" value
 * @method SpeakCategory       setDescription() Sets the current record's "description" value
 * @method SpeakCategory       setNetworkId()   Sets the current record's "network_id" value
 * @method SpeakCategory       setNetwork()     Sets the current record's "Network" value
 * @method SpeakCategory       setSpeakTopic()  Sets the current record's "SpeakTopic" collection
 * 
 * @package    Spark
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSpeakCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('speak_category');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('description', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('network_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Network', array(
             'local' => 'network_id',
             'foreign' => 'id'));

        $this->hasMany('SpeakTopic', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}