<?php

/**
 * BaseSpeakReply
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $body
 * @property string $htmlbody
 * @property integer $topic_id
 * @property integer $networkuser_id
 * @property SpeakTopic $SpeakTopic
 * @property NetworkUser $NetworkUser
 * 
 * @method integer     getId()             Returns the current record's "id" value
 * @method string      getBody()           Returns the current record's "body" value
 * @method string      getHtmlbody()       Returns the current record's "htmlbody" value
 * @method integer     getTopicId()        Returns the current record's "topic_id" value
 * @method integer     getNetworkuserId()  Returns the current record's "networkuser_id" value
 * @method SpeakTopic  getSpeakTopic()     Returns the current record's "SpeakTopic" value
 * @method NetworkUser getNetworkUser()    Returns the current record's "NetworkUser" value
 * @method SpeakReply  setId()             Sets the current record's "id" value
 * @method SpeakReply  setBody()           Sets the current record's "body" value
 * @method SpeakReply  setHtmlbody()       Sets the current record's "htmlbody" value
 * @method SpeakReply  setTopicId()        Sets the current record's "topic_id" value
 * @method SpeakReply  setNetworkuserId()  Sets the current record's "networkuser_id" value
 * @method SpeakReply  setSpeakTopic()     Sets the current record's "SpeakTopic" value
 * @method SpeakReply  setNetworkUser()    Sets the current record's "NetworkUser" value
 * 
 * @package    Spark
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSpeakReply extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('speak_reply');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('body', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('htmlbody', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('topic_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('networkuser_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SpeakTopic', array(
             'local' => 'topic_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('NetworkUser', array(
             'local' => 'networkuser_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}