<?php

/**
 * BaseWebuyDealAttribute
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $deal_id
 * @property string $attribute_name
 * @property string $attribute_value
 * @property WebuyDeal $WebuyDeal
 * 
 * @method integer            getId()              Returns the current record's "id" value
 * @method integer            getDealId()          Returns the current record's "deal_id" value
 * @method string             getAttributeName()   Returns the current record's "attribute_name" value
 * @method string             getAttributeValue()  Returns the current record's "attribute_value" value
 * @method WebuyDeal          getWebuyDeal()       Returns the current record's "WebuyDeal" value
 * @method WebuyDealAttribute setId()              Sets the current record's "id" value
 * @method WebuyDealAttribute setDealId()          Sets the current record's "deal_id" value
 * @method WebuyDealAttribute setAttributeName()   Sets the current record's "attribute_name" value
 * @method WebuyDealAttribute setAttributeValue()  Sets the current record's "attribute_value" value
 * @method WebuyDealAttribute setWebuyDeal()       Sets the current record's "WebuyDeal" value
 * 
 * @package    Spark
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWebuyDealAttribute extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('webuy_deal_attribute');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('deal_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('attribute_name', 'string', 155, array(
             'type' => 'string',
             'length' => 155,
             ));
        $this->hasColumn('attribute_value', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WebuyDeal', array(
             'local' => 'deal_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}