<?php

/**
 * BasePhotoLink
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $photo_id
 * @property integer $gallery_id
 * @property Photo $Photo
 * @property PhotoGallery $PhotoGallery
 * 
 * @method integer      getId()           Returns the current record's "id" value
 * @method integer      getPhotoId()      Returns the current record's "photo_id" value
 * @method integer      getGalleryId()    Returns the current record's "gallery_id" value
 * @method Photo        getPhoto()        Returns the current record's "Photo" value
 * @method PhotoGallery getPhotoGallery() Returns the current record's "PhotoGallery" value
 * @method PhotoLink    setId()           Sets the current record's "id" value
 * @method PhotoLink    setPhotoId()      Sets the current record's "photo_id" value
 * @method PhotoLink    setGalleryId()    Sets the current record's "gallery_id" value
 * @method PhotoLink    setPhoto()        Sets the current record's "Photo" value
 * @method PhotoLink    setPhotoGallery() Sets the current record's "PhotoGallery" value
 * 
 * @package    Spark
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhotoLink extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('photo_link');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('photo_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('gallery_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Photo', array(
             'local' => 'photo_id',
             'foreign' => 'id'));

        $this->hasOne('PhotoGallery', array(
             'local' => 'gallery_id',
             'foreign' => 'id'));
    }
}