<?php

/**
 * BaseMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $subject
 * @property string $body
 * @property string $htmlbody
 * @property integer $user_id
 * @property integer $network_id
 * @property sfGuardUser $sfGuardUser
 * @property Network $Network
 * @property Doctrine_Collection $MessageReciever
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getSubject()         Returns the current record's "subject" value
 * @method string              getBody()            Returns the current record's "body" value
 * @method string              getHtmlbody()        Returns the current record's "htmlbody" value
 * @method integer             getUserId()          Returns the current record's "user_id" value
 * @method integer             getNetworkId()       Returns the current record's "network_id" value
 * @method sfGuardUser         getSfGuardUser()     Returns the current record's "sfGuardUser" value
 * @method Network             getNetwork()         Returns the current record's "Network" value
 * @method Doctrine_Collection getMessageReciever() Returns the current record's "MessageReciever" collection
 * @method Message             setId()              Sets the current record's "id" value
 * @method Message             setSubject()         Sets the current record's "subject" value
 * @method Message             setBody()            Sets the current record's "body" value
 * @method Message             setHtmlbody()        Sets the current record's "htmlbody" value
 * @method Message             setUserId()          Sets the current record's "user_id" value
 * @method Message             setNetworkId()       Sets the current record's "network_id" value
 * @method Message             setSfGuardUser()     Sets the current record's "sfGuardUser" value
 * @method Message             setNetwork()         Sets the current record's "Network" value
 * @method Message             setMessageReciever() Sets the current record's "MessageReciever" collection
 * 
 * @package    Yuoweb
 * @subpackage model
 * @author     Shadley Wentzel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('message');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('subject', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('body', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('htmlbody', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('network_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Network', array(
             'local' => 'network_id',
             'foreign' => 'id'));

        $this->hasMany('MessageReciever', array(
             'local' => 'id',
             'foreign' => 'message_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}