<?php

/**
 * BasePhotoComment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $body
 * @property string $htmlbody
 * @property integer $networkuser_id
 * @property integer $photolink_id
 * @property NetworkUser $NetworkUser
 * @property PhotoLink $PhotoLink
 * 
 * @method integer      getId()             Returns the current record's "id" value
 * @method string       getBody()           Returns the current record's "body" value
 * @method string       getHtmlbody()       Returns the current record's "htmlbody" value
 * @method integer      getNetworkuserId()  Returns the current record's "networkuser_id" value
 * @method integer      getPhotolinkId()    Returns the current record's "photolink_id" value
 * @method NetworkUser  getNetworkUser()    Returns the current record's "NetworkUser" value
 * @method PhotoLink    getPhotoLink()      Returns the current record's "PhotoLink" value
 * @method PhotoComment setId()             Sets the current record's "id" value
 * @method PhotoComment setBody()           Sets the current record's "body" value
 * @method PhotoComment setHtmlbody()       Sets the current record's "htmlbody" value
 * @method PhotoComment setNetworkuserId()  Sets the current record's "networkuser_id" value
 * @method PhotoComment setPhotolinkId()    Sets the current record's "photolink_id" value
 * @method PhotoComment setNetworkUser()    Sets the current record's "NetworkUser" value
 * @method PhotoComment setPhotoLink()      Sets the current record's "PhotoLink" value
 * 
 * @package    Spark
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhotoComment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('photo_comment');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('body', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('htmlbody', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('networkuser_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('photolink_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NetworkUser', array(
             'local' => 'networkuser_id',
             'foreign' => 'id'));

        $this->hasOne('PhotoLink', array(
             'local' => 'photolink_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}