<?php

/**
 * BasePhotoGallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property integer $networkuser_id
 * @property integer $photo_count
 * @property NetworkUser $NetworkUser
 * @property Doctrine_Collection $PhotoLink
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getTitle()          Returns the current record's "title" value
 * @method integer             getNetworkuserId()  Returns the current record's "networkuser_id" value
 * @method integer             getPhotoCount()     Returns the current record's "photo_count" value
 * @method NetworkUser         getNetworkUser()    Returns the current record's "NetworkUser" value
 * @method Doctrine_Collection getPhotoLink()      Returns the current record's "PhotoLink" collection
 * @method PhotoGallery        setId()             Sets the current record's "id" value
 * @method PhotoGallery        setTitle()          Sets the current record's "title" value
 * @method PhotoGallery        setNetworkuserId()  Sets the current record's "networkuser_id" value
 * @method PhotoGallery        setPhotoCount()     Sets the current record's "photo_count" value
 * @method PhotoGallery        setNetworkUser()    Sets the current record's "NetworkUser" value
 * @method PhotoGallery        setPhotoLink()      Sets the current record's "PhotoLink" collection
 * 
 * @package    Spark
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhotoGallery extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('photo_gallery');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('networkuser_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('photo_count', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NetworkUser', array(
             'local' => 'networkuser_id',
             'foreign' => 'id'));

        $this->hasMany('PhotoLink', array(
             'local' => 'id',
             'foreign' => 'gallery_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}