<?php

/**
 * BasePhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $url
 * @property integer $networkuser_id
 * @property integer $view_count
 * @property integer $is_private
 * @property NetworkUser $NetworkUser
 * @property Doctrine_Collection $PhotoLink
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getUrl()            Returns the current record's "url" value
 * @method integer             getNetworkuserId()  Returns the current record's "networkuser_id" value
 * @method integer             getViewCount()      Returns the current record's "view_count" value
 * @method integer             getIsPrivate()      Returns the current record's "is_private" value
 * @method NetworkUser         getNetworkUser()    Returns the current record's "NetworkUser" value
 * @method Doctrine_Collection getPhotoLink()      Returns the current record's "PhotoLink" collection
 * @method Photo               setId()             Sets the current record's "id" value
 * @method Photo               setUrl()            Sets the current record's "url" value
 * @method Photo               setNetworkuserId()  Sets the current record's "networkuser_id" value
 * @method Photo               setViewCount()      Sets the current record's "view_count" value
 * @method Photo               setIsPrivate()      Sets the current record's "is_private" value
 * @method Photo               setNetworkUser()    Sets the current record's "NetworkUser" value
 * @method Photo               setPhotoLink()      Sets the current record's "PhotoLink" collection
 * 
 * @package    Yuoweb
 * @subpackage model
 * @author     Shadley Wentzel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('photo');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('url', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('networkuser_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('view_count', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_private', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('NetworkUser', array(
             'local' => 'networkuser_id',
             'foreign' => 'id'));

        $this->hasMany('PhotoLink', array(
             'local' => 'id',
             'foreign' => 'photo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $commentable0 = new Doctrine_Template_Commentable();
        $this->actAs($timestampable0);
        $this->actAs($commentable0);
    }
}