<?php

/**
 * BasePhotoGallery
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property integer $network_id
 * @property integer $user_id
 * @property integer $photo_count
 * @property boolean $is_private
 * @property sfGuardUser $sfGuardUser
 * @property Network $Network
 * @property Doctrine_Collection $PhotoLink
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getTitle()       Returns the current record's "title" value
 * @method integer             getNetworkId()   Returns the current record's "network_id" value
 * @method integer             getUserId()      Returns the current record's "user_id" value
 * @method integer             getPhotoCount()  Returns the current record's "photo_count" value
 * @method boolean             getIsPrivate()   Returns the current record's "is_private" value
 * @method sfGuardUser         getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Network             getNetwork()     Returns the current record's "Network" value
 * @method Doctrine_Collection getPhotoLink()   Returns the current record's "PhotoLink" collection
 * @method PhotoGallery        setId()          Sets the current record's "id" value
 * @method PhotoGallery        setTitle()       Sets the current record's "title" value
 * @method PhotoGallery        setNetworkId()   Sets the current record's "network_id" value
 * @method PhotoGallery        setUserId()      Sets the current record's "user_id" value
 * @method PhotoGallery        setPhotoCount()  Sets the current record's "photo_count" value
 * @method PhotoGallery        setIsPrivate()   Sets the current record's "is_private" value
 * @method PhotoGallery        setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method PhotoGallery        setNetwork()     Sets the current record's "Network" value
 * @method PhotoGallery        setPhotoLink()   Sets the current record's "PhotoLink" collection
 * 
 * @package    Yuoweb
 * @subpackage model
 * @author     Shadley Wentzel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePhotoGallery extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('photo_gallery');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('network_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('photo_count', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('is_private', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Network', array(
             'local' => 'network_id',
             'foreign' => 'id'));

        $this->hasMany('PhotoLink', array(
             'local' => 'id',
             'foreign' => 'gallery_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}