<?php

/**
 * BaseAdvertNetwork
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $advert_id
 * @property integer $network_id
 * @property integer $click_count
 * @property integer $position
 * @property boolean $is_active
 * @property Network $Network
 * @property Advert $Advert
 * 
 * @method integer       getId()          Returns the current record's "id" value
 * @method integer       getAdvertId()    Returns the current record's "advert_id" value
 * @method integer       getNetworkId()   Returns the current record's "network_id" value
 * @method integer       getClickCount()  Returns the current record's "click_count" value
 * @method integer       getPosition()    Returns the current record's "position" value
 * @method boolean       getIsActive()    Returns the current record's "is_active" value
 * @method Network       getNetwork()     Returns the current record's "Network" value
 * @method Advert        getAdvert()      Returns the current record's "Advert" value
 * @method AdvertNetwork setId()          Sets the current record's "id" value
 * @method AdvertNetwork setAdvertId()    Sets the current record's "advert_id" value
 * @method AdvertNetwork setNetworkId()   Sets the current record's "network_id" value
 * @method AdvertNetwork setClickCount()  Sets the current record's "click_count" value
 * @method AdvertNetwork setPosition()    Sets the current record's "position" value
 * @method AdvertNetwork setIsActive()    Sets the current record's "is_active" value
 * @method AdvertNetwork setNetwork()     Sets the current record's "Network" value
 * @method AdvertNetwork setAdvert()      Sets the current record's "Advert" value
 * 
 * @package    Yuoweb
 * @subpackage model
 * @author     Shadley Wentzel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdvertNetwork extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('advert_network');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('advert_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('network_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('click_count', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 2,
             ));
        $this->hasColumn('position', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Network', array(
             'local' => 'network_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Advert', array(
             'local' => 'advert_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}