<?php

/**
 * BaseSpeakTopic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property integer $category_id
 * @property integer $networkuser_id
 * @property SpeakCategory $SpeakCategory
 * @property NetworkUser $NetworkUser
 * @property Doctrine_Collection $SpeakReply
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method string              getTitle()          Returns the current record's "title" value
 * @method integer             getCategoryId()     Returns the current record's "category_id" value
 * @method integer             getNetworkuserId()  Returns the current record's "networkuser_id" value
 * @method SpeakCategory       getSpeakCategory()  Returns the current record's "SpeakCategory" value
 * @method NetworkUser         getNetworkUser()    Returns the current record's "NetworkUser" value
 * @method Doctrine_Collection getSpeakReply()     Returns the current record's "SpeakReply" collection
 * @method SpeakTopic          setId()             Sets the current record's "id" value
 * @method SpeakTopic          setTitle()          Sets the current record's "title" value
 * @method SpeakTopic          setCategoryId()     Sets the current record's "category_id" value
 * @method SpeakTopic          setNetworkuserId()  Sets the current record's "networkuser_id" value
 * @method SpeakTopic          setSpeakCategory()  Sets the current record's "SpeakCategory" value
 * @method SpeakTopic          setNetworkUser()    Sets the current record's "NetworkUser" value
 * @method SpeakTopic          setSpeakReply()     Sets the current record's "SpeakReply" collection
 * 
 * @package    Spark
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSpeakTopic extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('speak_topic');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('networkuser_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SpeakCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('NetworkUser', array(
             'local' => 'networkuser_id',
             'foreign' => 'id'));

        $this->hasMany('SpeakReply', array(
             'local' => 'id',
             'foreign' => 'topic_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}