<?php

/**
 * BaseNotificationType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property Doctrine_Collection $Notification
 * 
 * @method string              getTitle()        Returns the current record's "title" value
 * @method Doctrine_Collection getNotification() Returns the current record's "Notification" collection
 * @method NotificationType    setTitle()        Sets the current record's "title" value
 * @method NotificationType    setNotification() Sets the current record's "Notification" collection
 * 
 * @package    Yuoweb
 * @subpackage model
 * @author     Shadley Wentzel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotificationType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('notification_type');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Notification', array(
             'local' => 'id',
             'foreign' => 'notificationtype_id'));
    }
}