<?php

/**
 * ShoutMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShoutMessageTable extends PluginShoutMessageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShoutMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShoutMessage');
    }
}