# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  active_days: 30
  
  client:
    networkcount_max: 5
    
  network:
    featurecount_max: 6
    usercount_max:    100
    
  error_management:
    #record_exception_to_db:   true
    #record_php_error:  true
    #ask_user_to_comment:   true
    #after_comment_route:   @homepage
    #error_404_module:       idlErrorManagementTools          # To be called when a 404 error is raised
    #error_404_action:       convert404ToApplicationError     # Or when the requested URL doesn't match any
    #send_mail_on_error:         false           # To send an email when the error occurs
    #send_mail_on_user_comment:  false           # To send an email when a user comment an error
    #email_to:                   shad6ster@gmail.com
    #email_from:                 error@yuoweb.com
    
