<?php

/**
 * Advert
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Spark
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Advert extends BaseAdvert
{
	
/**
 * Function to find the advertnetwork objects 
 * 
 * This function retrieves all the advertnetwork objects associated to
 * an Advert Object
 * 
 * @param 
 * @return Doctrine_Collection All ADvertNetwork found
 */
	public function getAdvertNetworks()
	{
	  $q = Doctrine_Query::create()
       ->from('AdvertNetwork an')
       ->where('an.advert_id = ?', $this->getId());

     $features = Doctrine_Core::getTable('AdvertNetwork')->getWithNetworks($q);
     
     return (!empty($features)?$features:false);
	}	

}
