<?php

/**
 * AdvertTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdvertTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdvertTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Advert');
    }
}