<?php

/**
 * AdvertNetworkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdvertNetworkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdvertNetworkTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdvertNetwork');
    }
    
/**
 * Function to retrieve all the Network objects of an AdvertNetwork
 * 
 * This function finds all the AdvertNetwork with their assoiciated
 * Networks 
 * 
 * @param Doctrine_Query $q
 * 
 * @return query Base Query to find users on a network
 */ 
    public function getWithNetworks(Doctrine_Query $q = null)
    {
	  if (is_null($q))
	  {
	    $q = Doctrine_Query::create()
         ->from('AdvertNetwork an');
	  }	  
	  
      $q->leftJoin('an.Network n');
      
      return $q;
	  
    }
    
/**
 * Function to retrieve all the activenetwork objects
 * 
 * This function finds all the activenetworks with their assoiciated
 * Adverts 
 * 
 * @param Doctrine_Query $q
 * 
 * @return query Base Query to find users on a network
 */ 
    public function getWithAdverts(Doctrine_Query $q = null)
    {
	  if (is_null($q))
	  {
	    $q = Doctrine_Query::create()
         ->from('ActiveNetwork an');
	  }	  
	  
      $q->leftJoin('an.Advert r');
      
      return $q;
	  
    }
    
/**
 * Function to retrieve all the activenetwork objects with Adverts
 * 
 * This function finds all the activenetworks with their assoiciated
 * Adverts for the backend interface
 * 
 * @param Doctrine_Query $q
 * 
 * @return query Base Query to find users on a network
 */ 
	public function getBackendAdvertNetworksWithAdverts(Doctrine_Query $q = null)
	{
	    $rootAlias = $q->getRootAlias();
	 
	    $q->leftJoin($rootAlias . '.Advert');
	 
	    return $q;
		 
	  //echo '<pre>';print_r($q->fetchArray());exit;
	}
    
}