<?php

/**
 * ClientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Client');
    }
    
    public function retrieveByPk($PrimaryKey)
    {
	  $q = Doctrine_Query::create()
	    ->from('Client c')
	    ->where('c.id = ?', $PrimaryKey);
	 
	   return $q->execute();
    }
        	
	public function getActiveNetworks(Doctrine_Query $q = null)
	{
     return Doctrine_Core::getTable('Network')->getActiveNetworks($q);
	}
		
}