<?php

/**
 * Client
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Spark
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Client extends BaseClient
{
/**
 * Function to extend the base Save function
 * 
 * This function extends the base save function and sets the token of a client
 * 
 * @param $Doctrine_Connection $conn
 * 
 * @return void
 */
  public function save(Doctrine_Connection $conn = null)
  {      
	  if ($this->isNew())
	  {
	    $this->setToken(Yuoweb::slugify($this->getFullname()).'-client');
	  }	 
	  
	  return parent::save($conn);
  }
	
	public function getActiveNetworks($max = 10)
	{
	  $q = Doctrine_Query::create()
	    ->from('Network n')
	    ->where('n.client_id = ?', $this->getId())
	    ->limit($max);
	 
	  return Doctrine_Core::getTable('Network')->getActiveNetworks($q);
	}
	
	public function getAllNetworks(Doctrine_Query $q = null)
	{
	  $q = Doctrine_Query::create()
       ->from('Network n');
       
       return $q;
	}
	
	public function getNetworksForClient(Doctrine_Query $q = null)
	{
	  $q = Doctrine_Query::create()
       ->from('Network n')
       ->where('n.client_id = ?', $this->getId());
       
       return $q;
	}

}