<?php

/**
 * Client
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Spark
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Client extends BaseClient
{
	public function getActiveNetworks($max = 10)
	{
	  $q = Doctrine_Query::create()
	    ->from('Network n')
	    ->where('n.client_id = ?', $this->getId())
	    ->limit($max);
	 
	  return Doctrine_Core::getTable('Network')->getActiveNetworks($q);
	}
	
	public function getAllNetworks(Doctrine_Query $q = null)
	{
	  $q = Doctrine_Query::create()
       ->from('Network n')
       ->where('n.client_id = ?', $this->getId());
       
       return $q;
	}

}