<?php

/**
 * ConnectionResponseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConnectionResponseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConnectionResponseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConnectionResponse');
    }
}