<?php

/**
 * ConnectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConnectionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConnectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Connection');
    }
    
   public function getFriends(Doctrine_Query $q = null)
   {
	  if (is_null($q))
	  {
	    $q = Doctrine_Query::create()
         ->from('Connection c');
	  }	   

      $q->leftJoin('c.Reciever r')
	  	->andWhere('c.type_id = ?', 1);
	   //echo '<pre>';print_r($q->fetchArray());exit;
	   $Recievers = '';
	   	   
	   foreach ($q->fetchArray() as $value) { 
	   	$Recievers[$value['Reciever']['user_id']] = Doctrine_Core::getTable('sfGuardUser')->getUser($value['Reciever']['user_id']);
	   	$Recievers[$value['Reciever']['user_id']]['networkuser_id'] = $value['reciever_id'];
	   }
		
	   return $Recievers;
    }
    
   public function getFriendsWithFeeds (Doctrine_Query $q = null)
   {
	  if (is_null($q))
	  {
	    $q = Doctrine_Query::create()
         ->from('Connection c');
	  }	   
	  
	  $q->leftJoin('c.Reciever r')
	    ->leftJoin('r.Feed f')
	  	->andWhere('c.type_id = ?', 1);
	  //echo '<pre>';print_r($q->fetchArray());exit;
     return $q;
   }    

    
   public function getOwners(Doctrine_Query $q = null)
   {
	  if (is_null($q))
	  {
	    $q = Doctrine_Query::create()
         ->from('Connection c');
	  }	   

      $q->leftJoin('c.Owner o')
	  	->andWhere('c.type_id = ?', 1);
	   //echo '<pre>';print_r($q->fetchArray());exit;
	   $Owners = '';
	 
	   foreach ($q->fetchArray() as $value) { 
	   	$Owners[$value['Owner']['user_id']] = Doctrine_Core::getTable('sfGuardUser')->getUser($value['Owner']['user_id']);
	   	$Owners[$value['Owner']['user_id']]['networkuser_id'] = $value['reciever_id'];
	   }
		
	   return $Owners;
    }
}