<?php

/**
 * ConnectionTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConnectionTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConnectionTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConnectionType');
    }
    
}