<?php

/**
 * ConnectionStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConnectionStateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConnectionStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ConnectionState');
    }
}