<?php

/**
 * FeedTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeedTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FeedTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FeedType');
    }
}