<?php

/**
 * FeedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FeedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Feed');
    }
}