<?php

/**
 * FollowTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FollowTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FollowTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Follow');
    }
    
	/**
	 * This function find alls the feeds by using the follow
	 * table to find all the friends a user is following
	 *  
	 * @param Doctrine_Query $q Doctrine_Query
	 * @param integer $feed_limit Amount feed items to show.
	 * 
	 * @return array All Friends
	 */ 
   public function getFriendsWithFeedsWithLimit(Doctrine_Query $q = null, $feed_limit = 5)
   { 
	  if (is_null($q))
	  {
	    $q = Doctrine_Query::create()
         ->from('Follow f');
	  }	  
	
     return $this->fetchFriendsWithFeeds($q)->limit($feed_limit); 
   }  

	/**
	 * Function to render the base query for fetching feeds with their user details
	 *  
	 * @param Doctrine_Query $q Doctrine_Query
	 * 
	 * @return Doctrine_Query base query for fetching feeds with users
	 */ 
	public function fetchFriendsWithFeeds(Doctrine_Query $q = null)
	{
	  if (is_null($q))
	  {
	    $q = Doctrine_Query::create()
         ->from('Follow f');
	  }	   
	  
	  $q->leftJoin('f.Following fg')
	    ->leftJoin('fg.Feed fo')
	  	->orderBy('fo.created_at DESC');
 	  
     return $q; 
	}
}