<?php

/**
 * NetworkUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    yUoweb
 * @subpackage model
 * @author     Shadley Wentzel <shad6ster@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z Shadley Wentzel $
 */
class NetworkUser extends BaseNetworkUser
{
  /**
   * Returns the string representation of the object: "Full Name (username)"
   *
   * @return string
   */
  public function __toString()
  {
    $sfGuardUser  = $this->getsfGuardUser();

    return (string) $sfGuardUser[0]['username'];
  }	
     
  
/**
 * Function to return the associated sfGuardUser array for network user
 *  
 * @param q Doctrine_Query
 * 
 * @return array  sfGuardUser in array form 
 */
  public function getsfGuardUser()
  {
       $q = Doctrine_Query::create()
	      ->from('sfGuardUser sgu')
	      ->where('sgu.id = ?',  $this->getUserId()); 

	   return $q->fetchArray();		  	     
  }
  
/**
 * Function to return the associated sfGuardUser Object for network user
 *  
 * @param q Doctrine_Query
 * 
 * @return array  sfGuardUser Object
 */
  public function getsfGuardUserObject()
  {
       $q = Doctrine_Query::create()
	      ->from('sfGuardUser sgu')
	      ->where('sgu.id = ?',  $this->getUserId()); 

	   return $q->fetchOne();		  	     
  }

}    
