<?php

/**
 * NetworkFeatureTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NetworkFeatureTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NetworkFeatureTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NetworkFeature');
    }
    
/**
 * Function to retrieve all NetworkFeature objects with Feature Objects
 * 
 * This function will return all Feature objects for a NetworkFeature
 * 
 * @param Doctrine_Connection $conn 
 * 
 * @return query Base Query to find photos on a network
 */  
	public function getWithFeatures(Doctrine_Query $q = null)
	{
	  if (is_null($q))
	  {
	    $q = Doctrine_Query::create()
	      ->from('NetworkFeature nf');      	  
	  }
	  
	  $q->leftJoin('nf.Feature f')
      	->addOrderBy('nf.position ASC');

	   return $q;	
	  	     
	}
		
	public static function doSort($order)
	{ 	 
	  $con = Doctrine_Manager::connection();
	  	
	  try 
	  {
	    $con->beginTransaction();
		
	    foreach ($order as $rank => $id) 
	    {
	      $feature = Doctrine_Core::getTable('NetworkFeature')->findOneById($id);   
	        	
	      if($feature->position != ( ($rank + 1) * 10 ) )
	      {
	        //$feature = Doctrine_Core::getTable('NetworkFeature')->findOneByFeatureId($feature->id);
	        $feature->setPosition(( ($rank + 1) * 10));
	        $feature->save();
	      }
	    }

	    $con->commit();
	    
	    return true;    
	  }
	  catch (Exception $e)
	  {
	    $con->rollback();
	    return false;
	  }
	}
}