<?php

/**
 * NetworkTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NetworkTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NetworkTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NetworkType');
    }
}