<?php

/**
 * NetworkCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NetworkCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NetworkCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NetworkCategory');
    }
}