<?php

/**
 * NotificationTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotificationTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotificationTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotificationType');
    }
}