<?php

/**
 * PhotoViewTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhotoViewTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhotoViewTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PhotoView');
    }
}