<?php

/**
 * PhotoCommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhotoCommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhotoCommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PhotoComment');
    }
}