<?php

/**
 * PhotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Photo');
    }
    
/**
 * Function to find photos on a network
 * 
 * This function will find aall the photots on a given
 * network using the networkusers on the network
 * 
 * @param integer $NetworkId
 * 
 * @return query Base Query to find photos on a network
 */
	public function getPhotosForNetworkUsers($NetworkId)
	{
	  $q = Doctrine_Query::create()
	      ->from('Photo p')	  
          ->innerJoin('p.NetworkUser nu')
          ->where('nu.network_id = ?', $NetworkId);
		
	  return $q;	
	}
}