<?php

/**
 * PhotoGalleryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PhotoGalleryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PhotoGalleryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PhotoGallery');
    }
}