<?php

/**
 * WebuyDealTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebuyDealTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebuyDealTable
     */
    public static function getInstance()
    {
      return Doctrine_Core::getTable('WebuyDeal');
    }
    
   /**
	 * Function to find producs on a for a deal
	 * 
	 * This function will find all  products for deals
	 * 
	 * @param  void
	 * 
	 * @return query Base Query to find products for a deal
	*/
	public function getWithProducts(Doctrine_Query $q = null)
	{
	  if (is_null($q))
	  {
	    $q = Doctrine_Query::create()
	      ->from('WebuyDeal wd');
	  }
	  
	  $q->leftJoin('wd.WebuyProduct wbp');
		
	  return $q;	
	}
}