<?php

/**
 * WebuyDealTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebuyDealTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebuyDealTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WebuyDeal');
    }
}