<?php

/**
 * BaseShoutClient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $client_id
 * @property integer $network_id
 * @property integer $country_id
 * @property string $username
 * @property string $password
 * @property string $api_id
 * @property integer $message_count
 * @property decimal $credit_left
 * @property integer $local_only
 * @property string $dialing_code
 * @property Client $Client
 * @property Network $Network
 * @property Doctrine_Collection $ShoutMessage
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method integer             getClientId()      Returns the current record's "client_id" value
 * @method integer             getNetworkId()     Returns the current record's "network_id" value
 * @method integer             getCountryId()     Returns the current record's "country_id" value
 * @method string              getUsername()      Returns the current record's "username" value
 * @method string              getPassword()      Returns the current record's "password" value
 * @method string              getApiId()         Returns the current record's "api_id" value
 * @method integer             getMessageCount()  Returns the current record's "message_count" value
 * @method decimal             getCreditLeft()    Returns the current record's "credit_left" value
 * @method integer             getLocalOnly()     Returns the current record's "local_only" value
 * @method string              getDialingCode()   Returns the current record's "dialing_code" value
 * @method Client              getClient()        Returns the current record's "Client" value
 * @method Network             getNetwork()       Returns the current record's "Network" value
 * @method Doctrine_Collection getShoutMessage()  Returns the current record's "ShoutMessage" collection
 * @method ShoutClient         setId()            Sets the current record's "id" value
 * @method ShoutClient         setClientId()      Sets the current record's "client_id" value
 * @method ShoutClient         setNetworkId()     Sets the current record's "network_id" value
 * @method ShoutClient         setCountryId()     Sets the current record's "country_id" value
 * @method ShoutClient         setUsername()      Sets the current record's "username" value
 * @method ShoutClient         setPassword()      Sets the current record's "password" value
 * @method ShoutClient         setApiId()         Sets the current record's "api_id" value
 * @method ShoutClient         setMessageCount()  Sets the current record's "message_count" value
 * @method ShoutClient         setCreditLeft()    Sets the current record's "credit_left" value
 * @method ShoutClient         setLocalOnly()     Sets the current record's "local_only" value
 * @method ShoutClient         setDialingCode()   Sets the current record's "dialing_code" value
 * @method ShoutClient         setClient()        Sets the current record's "Client" value
 * @method ShoutClient         setNetwork()       Sets the current record's "Network" value
 * @method ShoutClient         setShoutMessage()  Sets the current record's "ShoutMessage" collection
 * 
 * @package    Yuoweb
 * @subpackage model
 * @author     Shadley Wentzel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseShoutClient extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shout_client');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('client_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('network_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('country_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('username', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('password', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('api_id', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));
        $this->hasColumn('message_count', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('credit_left', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 10,
             ));
        $this->hasColumn('local_only', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('dialing_code', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Client', array(
             'local' => 'client_id',
             'foreign' => 'id'));

        $this->hasOne('Network', array(
             'local' => 'network_id',
             'foreign' => 'id'));

        $this->hasMany('ShoutMessage', array(
             'local' => 'id',
             'foreign' => 'shoutclient_id'));

        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'client_id',
              1 => 'network_id',
              2 => 'api_id',
             ),
             ));
        $softdelete0 = new Doctrine_Template_SoftDelete();
        $this->actAs($searchable0);
        $this->actAs($softdelete0);
    }
}