<?php

/**
 * PluginHeadspacePostTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginHeadspacePostTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginHeadspacePostTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginHeadspacePostTag');
    }
}