<?php

/**
 * PluginHeadspaceTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginHeadspaceTagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginHeadspaceTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginHeadspaceTag');
    }
}