<?php

/**
 * PluginHeadspacePostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginHeadspacePostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginHeadspacePostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginHeadspacePost');
    }
}