<?php

/**
 * sfGuardUserGroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserGroupTable extends PluginsfGuardUserGroupTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUserGroup');
    }
    
	public function getUserWithProfile($UserID)
	{ 
	  $q = Doctrine_Query::create()
	  	  ->from('sfGuardUser su')
		  ->leftJoin('su.UserProfile up')
	      >where('su.user_id = ?', $UserID);	  
	  
	  return $q->fetchOne();     
	}
}