<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Spark
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
/**
 * Function to return the full name of a user object
 * 
 * This function combines the firt_name and last_name of an user object
 * and uses them to return the full name
 * 
 * @param 
 * @return string Full Name of User
 */	
 public function getFullname(){
		return ucwords( $this->getFirstName().' '.$this->getLastName());
	}
	
/**
 * Function to return the UserProfile Object associated to a sfGuardUser Object
 * 
 * This function return the associated UserProfile Object using the user_id attribute
 * of a sfGuardUser Object
 * 
 * @param 
 * @return UserProfile UserProfile Object
 */	
 public function getSfGuardUserWithUserProfile()
 {
	 $q = Doctrine_Query::create()
	   ->from('UserProfile up')
	   ->where('up.sfuser_id = ?', $this->getId());
	      
	return $q; 	
 }
}