<?php

/**
 * PluginWebuyDealAttributeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWebuyDealAttributeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWebuyDealAttributeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWebuyDealAttribute');
    }
}