<?php

/**
 * PluginWebuyNetworkUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWebuyNetworkUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWebuyNetworkUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWebuyNetworkUser');
    }
}