<?php

/**
 * PluginWebuyProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWebuyProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWebuyProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWebuyProduct');
    }
}