<?php

/**
 * PluginWebuyDealTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWebuyDealTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWebuyDealTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWebuyDeal');
    }
    
   /**
	 * Function to find producs on a for a deal
	 * 
	 * This function will find all  products for deals
	 * 
	 * @param Doctrine_Query $q Doctrine_Query
	 * 
	 * @return query Base Query to find products for a deal
	*/
	public function getWithProducts(Doctrine_Query $q = null)
	{
	  if (is_null($q))
	  {
	    $q = Doctrine_Query::create()
	      ->from('WebuyDeal wd');
	  }
	  
	  $q->leftJoin('wd.WebuyProduct wbp');
		
	  return $q;	
	}
	
/**
 * Function to find a all the deals for a network with their associated products
 * 
 * @param integer $NetworkId Id of network to find deals for
 * 
 * @return query Base Query to find deals with products
 */
	public function getDealsWithProducts($NetworkId)
	{	  
	  $rootAlias = $q->getRootAlias();
	  
	  $q->where($rootAlias.'.network_id = ?', $NetworkId)
	    ->leftJoin($rootAlias . '.wd.WebuyProduct wbp');
		
	  return $q;	
	}
}