<?php

/**
 * PluginWebuyDealTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginWebuyDealTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginWebuyDealTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginWebuyDeal');
    }
}