<?php

/**
 * WebuyDealAttributeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebuyDealAttributeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebuyDealAttributeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WebuyDealAttribute');
    }
}