<?php

/**
 * WebuyCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebuyCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebuyCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WebuyCategory');
    }
}