<?php

/**
 * WebuySupplierTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebuySupplierTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebuySupplierTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WebuySupplier');
    }
}