<?php

/**
 * WebuyNetworkUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebuyNetworkUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebuyNetworkUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WebuyNetworkUser');
    }
}