<?php

/**
 * PluginShoutCountryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginShoutCountryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginShoutCountryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginShoutCountry');
    }
}