<?php

/**
 * PluginShoutClientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginShoutClientTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginShoutClientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginShoutClient');
    }
}