<?php

/**
 * BaseWebuyCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $title
 * @property Doctrine_Collection $WebuyProduct
 * 
 * @method string              getTitle()        Returns the current record's "title" value
 * @method Doctrine_Collection getWebuyProduct() Returns the current record's "WebuyProduct" collection
 * @method WebuyCategory       setTitle()        Sets the current record's "title" value
 * @method WebuyCategory       setWebuyProduct() Sets the current record's "WebuyProduct" collection
 * 
 * @package    Yuoweb
 * @subpackage model
 * @author     Shadley Wentzel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWebuyCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('webuy_category');
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('WebuyProduct', array(
             'local' => 'id',
             'foreign' => 'category_id'));
    }
}