<?php

/**
 * BaseWebuyDeal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $product_id
 * @property integer $network_id
 * @property string $title
 * @property decimal $full_price
 * @property decimal $deal_price
 * @property decimal $discount_percent
 * @property integer $buyer_count
 * @property integer $tipping_count
 * @property integer $status
 * @property integer $g_lat
 * @property integer $g_long
 * @property timestamp $expires_at
 * @property WebuyProduct $WebuyProduct
 * @property Network $Network
 * @property Doctrine_Collection $WebuyDealAttribute
 * @property Doctrine_Collection $WebuyNetworkUser
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method integer             getProductId()          Returns the current record's "product_id" value
 * @method integer             getNetworkId()          Returns the current record's "network_id" value
 * @method string              getTitle()              Returns the current record's "title" value
 * @method decimal             getFullPrice()          Returns the current record's "full_price" value
 * @method decimal             getDealPrice()          Returns the current record's "deal_price" value
 * @method decimal             getDiscountPercent()    Returns the current record's "discount_percent" value
 * @method integer             getBuyerCount()         Returns the current record's "buyer_count" value
 * @method integer             getTippingCount()       Returns the current record's "tipping_count" value
 * @method integer             getStatus()             Returns the current record's "status" value
 * @method integer             getGLat()               Returns the current record's "g_lat" value
 * @method integer             getGLong()              Returns the current record's "g_long" value
 * @method timestamp           getExpiresAt()          Returns the current record's "expires_at" value
 * @method WebuyProduct        getWebuyProduct()       Returns the current record's "WebuyProduct" value
 * @method Network             getNetwork()            Returns the current record's "Network" value
 * @method Doctrine_Collection getWebuyDealAttribute() Returns the current record's "WebuyDealAttribute" collection
 * @method Doctrine_Collection getWebuyNetworkUser()   Returns the current record's "WebuyNetworkUser" collection
 * @method WebuyDeal           setId()                 Sets the current record's "id" value
 * @method WebuyDeal           setProductId()          Sets the current record's "product_id" value
 * @method WebuyDeal           setNetworkId()          Sets the current record's "network_id" value
 * @method WebuyDeal           setTitle()              Sets the current record's "title" value
 * @method WebuyDeal           setFullPrice()          Sets the current record's "full_price" value
 * @method WebuyDeal           setDealPrice()          Sets the current record's "deal_price" value
 * @method WebuyDeal           setDiscountPercent()    Sets the current record's "discount_percent" value
 * @method WebuyDeal           setBuyerCount()         Sets the current record's "buyer_count" value
 * @method WebuyDeal           setTippingCount()       Sets the current record's "tipping_count" value
 * @method WebuyDeal           setStatus()             Sets the current record's "status" value
 * @method WebuyDeal           setGLat()               Sets the current record's "g_lat" value
 * @method WebuyDeal           setGLong()              Sets the current record's "g_long" value
 * @method WebuyDeal           setExpiresAt()          Sets the current record's "expires_at" value
 * @method WebuyDeal           setWebuyProduct()       Sets the current record's "WebuyProduct" value
 * @method WebuyDeal           setNetwork()            Sets the current record's "Network" value
 * @method WebuyDeal           setWebuyDealAttribute() Sets the current record's "WebuyDealAttribute" collection
 * @method WebuyDeal           setWebuyNetworkUser()   Sets the current record's "WebuyNetworkUser" collection
 * 
 * @package    Yuoweb
 * @subpackage model
 * @author     Shadley Wentzel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWebuyDeal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('webuy_deal');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('network_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('title', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('full_price', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 10,
             ));
        $this->hasColumn('deal_price', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 10,
             ));
        $this->hasColumn('discount_percent', 'decimal', 10, array(
             'type' => 'decimal',
             'scale' => 2,
             'length' => 10,
             ));
        $this->hasColumn('buyer_count', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('tipping_count', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('g_lat', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('g_long', 'integer', null, array(
             'type' => 'integer',
             'default' => 0,
             ));
        $this->hasColumn('expires_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('WebuyProduct', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Network', array(
             'local' => 'network_id',
             'foreign' => 'id'));

        $this->hasMany('WebuyDealAttribute', array(
             'local' => 'id',
             'foreign' => 'deal_id'));

        $this->hasMany('WebuyNetworkUser', array(
             'local' => 'id',
             'foreign' => 'deal_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'description',
             ),
             ));
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'title',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($searchable0);
        $this->actAs($sluggable0);
    }
}