<?php

/**
 * sfMultisiteThemeThemeInfoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfMultisiteThemeThemeInfoTable extends PluginsfMultisiteThemeThemeInfoTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfMultisiteThemeThemeInfoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfMultisiteThemeThemeInfo');
    }
}