<?php

/**
 * sfMultisiteThemeProfileHostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfMultisiteThemeProfileHostTable extends PluginsfMultisiteThemeProfileHostTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfMultisiteThemeProfileHostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfMultisiteThemeProfileHost');
    }
	
	public function getThemeProfileWithTheme(Doctrine_Query $q = null)
	{
	  if (is_null($q))
	  {
	   $q = Doctrine_Query::create()
      	    ->from('sfMultisiteThemeProfile smtp');      	  
	  }
	 
	  $q->leftJoin('smtph.sfMultisiteThemeProfile smtp');
       
      return Doctrine_Core::getTable('sfMultisiteThemeProfile')->getWithTheme($q);
	}
}