<?php

/**
 * HeadspacePostTagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HeadspacePostTagTable extends PluginHeadspacePostTagTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object HeadspacePostTagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HeadspacePostTag');
    }
}