<?php

/**
 * HeadspacePostTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Yuoweb
 * @subpackage model
 * @author     Shadley Wentzel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class HeadspacePostTag extends PluginHeadspacePostTag
{

}