<?php

/**
 * HeadspacePostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HeadspacePostTable extends PluginHeadspacePostTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object HeadspacePostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HeadspacePost');
    }
}