<?php

/**
 * HeadspaceTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    yUoweb
 * @subpackage model
 * @author     Shadley Wentzel
 * @version    
 */
class HeadspaceTag extends PluginHeadspaceTag
{
	/**
	 * Function to return a string representaion of an HeadspaceTag Object
	 * 
	 * @param void
	 * 
	 * @return string Representation of Creditnotetype Object
	 * 
	 */
	public function __toString()
	{
	    return $this->getTag();
	}
}