# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

prod:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=127.0.0.1;dbname=yuoweb
      username: yuoweb
      password: 1qa2ws3ed4rf

dev:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=127.0.0.1;dbname=yuoweb
      username: yuoweb
      password: 1qa2ws3ed4rf
 
test:   
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn:      mysql:host=127.0.0.1;dbname=yuowebtest
      username: yuowebtest
      password: 1qa2ws3ed4rf
