generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Advert
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          advert
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
       display: [ title, url, url, created_at]
       sort:  [ created_at, desc ]
       title: '<h2>Adverts</h2>'
       max_per_page: 10
      filter:  
        class: false
      form:
        class:     BackendAdvertForm
      edit:    
        title: '<h3>Editing Advert "%%title%%"</h3>'
      new:     ~
