<?php

/**
 * SpeakoutReplyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpeakoutReplyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SpeakoutReplyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SpeakoutReply');
    }
    
	public function getReplysWithUsers(Doctrine_Query $q = null)
	{
	  if (is_null($q))
	  {
	    $q = Doctrine_Query::create()
	      ->from('NetworkUser nu');      	  
	  }
	
	  return Doctrine_Core::getTable('NetworkUser')->getWithUsers($q);
		 
	  //echo '<pre>';print_r($q->fetchArray());exit;
	}
}