<?php

/**
 * BaseHeadspaceTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $network_id
 * @property integer $networkuser_id
 * @property integer $count
 * @property string $tag
 * @property Network $Network
 * @property NetworkUser $NetworkUser
 * @property Doctrine_Collection $HeadspacePostTag
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method integer             getNetworkId()        Returns the current record's "network_id" value
 * @method integer             getNetworkuserId()    Returns the current record's "networkuser_id" value
 * @method integer             getCount()            Returns the current record's "count" value
 * @method string              getTag()              Returns the current record's "tag" value
 * @method Network             getNetwork()          Returns the current record's "Network" value
 * @method NetworkUser         getNetworkUser()      Returns the current record's "NetworkUser" value
 * @method Doctrine_Collection getHeadspacePostTag() Returns the current record's "HeadspacePostTag" collection
 * @method HeadspaceTag        setId()               Sets the current record's "id" value
 * @method HeadspaceTag        setNetworkId()        Sets the current record's "network_id" value
 * @method HeadspaceTag        setNetworkuserId()    Sets the current record's "networkuser_id" value
 * @method HeadspaceTag        setCount()            Sets the current record's "count" value
 * @method HeadspaceTag        setTag()              Sets the current record's "tag" value
 * @method HeadspaceTag        setNetwork()          Sets the current record's "Network" value
 * @method HeadspaceTag        setNetworkUser()      Sets the current record's "NetworkUser" value
 * @method HeadspaceTag        setHeadspacePostTag() Sets the current record's "HeadspacePostTag" collection
 * 
 * @package    Yuoweb
 * @subpackage model
 * @author     Shadley Wentzel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHeadspaceTag extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('headspace_tag');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('network_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('networkuser_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('count', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('tag', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Network', array(
             'local' => 'network_id',
             'foreign' => 'id'));

        $this->hasOne('NetworkUser', array(
             'local' => 'networkuser_id',
             'foreign' => 'id'));

        $this->hasMany('HeadspacePostTag', array(
             'local' => 'id',
             'foreign' => 'tag_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'id',
              1 => 'tag',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($searchable0);
    }
}