<?php

/**
 * BaseHeadspacePost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $network_id
 * @property integer $networkuser_id
 * @property string $subject
 * @property string $body
 * @property string $html_body
 * @property integer $allow_comments
 * @property integer $status
 * @property Network $Network
 * @property NetworkUser $NetworkUser
 * @property Doctrine_Collection $HeadspaceTag
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method integer             getNetworkId()      Returns the current record's "network_id" value
 * @method integer             getNetworkuserId()  Returns the current record's "networkuser_id" value
 * @method string              getSubject()        Returns the current record's "subject" value
 * @method string              getBody()           Returns the current record's "body" value
 * @method string              getHtmlBody()       Returns the current record's "html_body" value
 * @method integer             getAllowComments()  Returns the current record's "allow_comments" value
 * @method integer             getStatus()         Returns the current record's "status" value
 * @method Network             getNetwork()        Returns the current record's "Network" value
 * @method NetworkUser         getNetworkUser()    Returns the current record's "NetworkUser" value
 * @method Doctrine_Collection getHeadspaceTag()   Returns the current record's "HeadspaceTag" collection
 * @method HeadspacePost       setId()             Sets the current record's "id" value
 * @method HeadspacePost       setNetworkId()      Sets the current record's "network_id" value
 * @method HeadspacePost       setNetworkuserId()  Sets the current record's "networkuser_id" value
 * @method HeadspacePost       setSubject()        Sets the current record's "subject" value
 * @method HeadspacePost       setBody()           Sets the current record's "body" value
 * @method HeadspacePost       setHtmlBody()       Sets the current record's "html_body" value
 * @method HeadspacePost       setAllowComments()  Sets the current record's "allow_comments" value
 * @method HeadspacePost       setStatus()         Sets the current record's "status" value
 * @method HeadspacePost       setNetwork()        Sets the current record's "Network" value
 * @method HeadspacePost       setNetworkUser()    Sets the current record's "NetworkUser" value
 * @method HeadspacePost       setHeadspaceTag()   Sets the current record's "HeadspaceTag" collection
 * 
 * @package    Yuoweb
 * @subpackage model
 * @author     Shadley Wentzel
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHeadspacePost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('headspace_post');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('network_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('networkuser_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('subject', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('html_body', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('allow_comments', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('status', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Network', array(
             'local' => 'network_id',
             'foreign' => 'id'));

        $this->hasOne('NetworkUser', array(
             'local' => 'networkuser_id',
             'foreign' => 'id'));

        $this->hasMany('HeadspaceTag', array(
             'local' => 'id',
             'foreign' => 'post_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $commentable0 = new Doctrine_Template_Commentable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'subject',
             ),
             'canUpdate' => true,
             ));
        $searchable0 = new Doctrine_Template_Searchable(array(
             'fields' => 
             array(
              0 => 'id',
              1 => 'subject',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($commentable0);
        $this->actAs($sluggable0);
        $this->actAs($searchable0);
    }
}