generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardPermission
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_permission
    with_doctrine_route:   true

    config:
      list:
        title: '<h2>Permission list</h2>'
        display: [=name, description, created_at, updated_at]
        
      filter:
        class: false

      edit:
        title: '<h2>Editing Permission "%%name%%"</h2>'

      new:
        title: '<h2>New Permission</h2>'

      form:
        display: [name, description, groups_list, users_list]