<?php use_stylesheet('network.css') ?>
<?php use_helper('Text') ?>
<?php slot( 'pagetitle', 'yUoWeb - Showing Network: '.$network->getTitle()  )?> <h3><?php echo __('Details') ?></h3>
  <?php if ($network->getLogo()): ?>    <div class="logo">      <a href="<?php echo $network->getUrl() ?>">        <img src="/uploads/networks/<?php echo $job->getLogo() ?>"          alt="<?php echo $network->getClient() ?> logo" />      </a>    </div>  <?php endif; ?>   <div class="description">    <?php echo simple_format_text($network->getDescription()) ?>  </div>
  <div style="padding: 20px 0;">    <a href="<?php echo url_for('network/edit?id='.$network->getId()) ?>">      <?php echo __('Edit')?>    </a>  </div>
    <div class="tabsholder">
	<div id="tabs">		<ul>			<li><a href="#tabs-1"><?php echo __('Personality') ?></a></li>			<li><a href="#tabs-2"><?php echo __('Layout') ?></a></li>			<li><a href="#tabs-3"><?php echo __('Theme') ?></a></li>		</ul>				<div id="tabs-1">			<h3>Give your personality</h3>			<p>				By giving your network a personality it will miraculousy be				created with features that show its personality.			</p>			<p>			</p>			<p>								<button class="personality_item">current</button>			</p>			<p>								<button class="personality_item">sports star</button>				<button class="personality_item">social lite</button>				<button class="personality_item">super shopper</button>			</p>		</div>
		<div id="tabs-2">			<h3>Change your layout</h3>			<p>				Customize your layout features the way you want. Drag the features				around to change their order			</p>			  <div id="network_layout">			  	<ul id="featurelist" class="droppable">			  		<li id="title" class="nonsortable">Title</li>			  		<li id="navigation" class="nonsortable">Navigation</li>			  	<?php foreach ( $features as $feature ): ?>			  		<li id="<?php echo $feature['id']; ?>" class="sortable">			  			<?php echo $feature['Feature']['title'] ?>			  			<span id="<?php echo $feature['id']; ?>" class="featurelist_remove"><img src="/images/delete.png"></span>			  		</li>			  	<?php endforeach; ?>			  		<li id="footer" class="nonsortable">Footer</li>			  	</ul>			  </div>					  <ul id="availblefeaturelist">			  	<?php $availibleFeatures = $availibleFeatures->getRawValue() ?>			  	<?php foreach ( $availibleFeatures as $availibleFeature ): ?>			  		<?php if (is_array($availibleFeature)) :?>			  			<li> 							<small><?php echo $availibleFeature['title'] ?></small>							<span id="<?php echo $availibleFeature['id']; ?>" class="featurelist_add"><img src="/images/new.png"></span>						</li>			  		<?php endif; ?>			  	<?php endforeach; ?>			  </ul>			  			  <div class="clearer"></div>
		</div>
		<div id="tabs-3">				<h3>Change your look</h3>				<p>					Customize the way your network will look, click the look you like and 					it will be applied to yout network				</p>				<h5><?php echo ('Current Theme')?> </h5>				<span id="currenttheme">					<img src="<?php echo "http://".$_SERVER['SERVER_NAME'].$sf_request->getRelativeUrlRoot()."/themes/".$theme[0]['sfMultisiteThemeProfile']['sfMultisiteThemeThemeInfo']['theme_name']."/template.png" ?>">  		        </span>		        <br>		        <h5><?php echo ('Availible Themes')?> </h5>				<ul id="availiblethemes">					<?php $count = 0; ?>					<?php foreach ($availiblethemes as $availibetheme) :?>						<li>							<img id="<?php echo $availibetheme['id'] ?>" class="availiblethemes_item" src="<?php echo "http://".$_SERVER['SERVER_NAME'].$sf_request->getRelativeUrlRoot()."/themes/".$availibetheme['theme_name']."/template_small.png" ?>"> 						</li>						<?php $count ++; ?> 						<?php if ($count == 4) :?>						 <br>						<?php endif;?>					<?php endforeach; ?>				</ul>				<div class="clearer"></div>		</div>
	   </div>
  </div> <script type="text/javascript">$(document).ready(  function()   {    $("#featurelist").sortable(    {       items: '.sortable',      update: function(event, ui)       {		var featureOrder = $(this).sortable('toArray').toString();		$.post('<?php echo url_for('@feature_reorder')?>', {featureOrder:featureOrder});      }          } );
    $( "#featurelist li.nonsortable" ).disableSelection();	    $(".draggable").draggable({    	   revert: true,    	   opacity: .75,    	   containment: '#tabs-2',    	   cursor: 'move',    	   cursorAt: { top: 35, left: 45 },    	   helper: function(event) {    	   return $('<div>' + $(this).children("small").text() + '</div>');    	   },    	   drag: function(event, ui) {    	   $('.droppable').removeClass('drophighlight')    	                  .find('p')    	                  .html('Drop it!<br/>Right here, right now.');    	   }    	});	$('.featurelist_add').click(function() {		$.ajax({		   type: "POST",		   url: "<?php echo url_for('@feature_additem') ?>",		   data: ({id : this.getAttribute('id')}),		   dataType: "html",		   		   success: function(data){		       $('#tabs-2').html(data);		   }		 }).responseText;	});	$('.featurelist_remove').click(function() {		$.ajax({		   type: "POST",		   url: "<?php echo url_for('@feature_removeitem') ?>",		   data: ({id : this.getAttribute('id')}),		   dataType: "html",		   		   success: function(data){		       $('#tabs-2').html(data);		   }		 }).responseText;	});				$('.availiblethemes_item').click(function() {		$.ajax({		   type: "POST",		   url: "<?php echo url_for('network_changetheme') ?>",		   data: ({theme : this.getAttribute('id')}),		   dataType: "html",		   		   success: function(data){		     $('#currenttheme').html(data);		   }		 }).responseText;	});});  $(function() {	$( "#tabs" ).tabs();});</script>