<?php

/**
 * ApplicationErrorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ApplicationErrorTable extends PluginApplicationErrorTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ApplicationErrorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ApplicationError');
    }
}